{{- if .Values.secret.create -}}
{{- if eq .Values.secret.DATABASE_DSN "CHANGE_ME" -}}
{{- fail "secret.DATABASE_DSN must be set (replace CHANGE_ME with actual DSN)" -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alertmanager-webhook-relay.fullname" . }}
  labels:
    {{- include "alertmanager-webhook-relay.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_DSN: {{ .Values.secret.DATABASE_DSN | quote }}
  PACHCA_TOKEN: {{ .Values.secret.PACHCA_TOKEN | quote }}
  EMAIL_USERNAME: {{ .Values.secret.EMAIL_USERNAME | quote }}
  EMAIL_PASSWORD: {{ .Values.secret.EMAIL_PASSWORD | quote }}
{{- end }}
